choco install dotnet4.5
choco install dotnet4.5.1
choco install microsoftsecurityessentials
choco install malwarebytes
choco install webdeploy
choco install powershell4
choco install boxstarter
choco install foxitreader
choco install baretail
choco install totalcommander
choco install nunit
choco install svn
choco install ferventcoder.chocolatey.utilities
choco install visualstudio2013ultimate
choco install visualstudio2013-webessentials.vsix
choco install sqlserver2014express
choco install google-chrome-x64
choco install chromedriver2
choco install notepadplusplus
choco install octopusdeploy.tentacle